// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxCq5Eld_a-HKjnMecTLI7aO_WWDymw0',
    appId: '1:408490960747:web:8e3b8f10add7e430f00e2e',
    messagingSenderId: '408490960747',
    projectId: 'triptide-ef65d',
    authDomain: 'triptide-ef65d.firebaseapp.com',
    storageBucket: 'triptide-ef65d.firebasestorage.app',
    measurementId: 'G-S97W3DYZP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdX8zQtFBBk9m-XXu09PXwFKoDVsHHo4M',
    appId: '1:408490960747:android:f550a87697f15b1ff00e2e',
    messagingSenderId: '408490960747',
    projectId: 'triptide-ef65d',
    storageBucket: 'triptide-ef65d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4gITBdihiDZxwwqiHjvsaR0JsHGFUWfc',
    appId: '1:408490960747:ios:92a54db6a3a7a899f00e2e',
    messagingSenderId: '408490960747',
    projectId: 'triptide-ef65d',
    storageBucket: 'triptide-ef65d.firebasestorage.app',
    androidClientId: '408490960747-ru1s4107i77eqs8jralln5tns2k21pap.apps.googleusercontent.com',
    iosClientId: '408490960747-f8ni6qt8sujvc8tu29u1nb3qfro1bfhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.triptide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4gITBdihiDZxwwqiHjvsaR0JsHGFUWfc',
    appId: '1:408490960747:ios:92a54db6a3a7a899f00e2e',
    messagingSenderId: '408490960747',
    projectId: 'triptide-ef65d',
    storageBucket: 'triptide-ef65d.firebasestorage.app',
    androidClientId: '408490960747-ru1s4107i77eqs8jralln5tns2k21pap.apps.googleusercontent.com',
    iosClientId: '408490960747-f8ni6qt8sujvc8tu29u1nb3qfro1bfhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.triptide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaxCq5Eld_a-HKjnMecTLI7aO_WWDymw0',
    appId: '1:408490960747:web:8454ac0e1f4cafc3f00e2e',
    messagingSenderId: '408490960747',
    projectId: 'triptide-ef65d',
    authDomain: 'triptide-ef65d.firebaseapp.com',
    storageBucket: 'triptide-ef65d.firebasestorage.app',
    measurementId: 'G-SPFXD9VRYK',
  );
}
